services:
  orchestrator:
    build: .
    container_name: orchestrator
    environment:
      - MONGO_USER=iotuser
      - MONGO_PASS=iotpass
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=iot_mesh
      - MONGO_COLLECTION=sensor_data
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_TOPIC=mesh/data/
      - MQTT_USERNAME=orchestrator
      - MQTT_PASSWORD=mqtt_pass
    restart: always